CREATE DATABASE IF NOT EXISTS devbook;
USE devbook;

DROP TABLE IF EXISTS USUARIOS;
CREATE TABLE USUARIOS (
    ID INT AUTO_INCREMENT PRIMARY KEY,
    NOME VARCHAR(50) NOT NULL,
    NICK VARCHAR(50) NOT NULL UNIQUE, /*UNIQUE - CHAVE ÚNICA*/
    EMAIL VARCHAR(50) NOT NULL UNIQUE, /*UNIQUE - CHAVE ÚNICA*/
    SENHA VARCHAR(50) NOT NULL,
    CRIADOEM TIMESTAMP DEFAULT CURRENT_TIMESTAMP()/*DEFINIDO QUE A CRIAÇÃO SERÁ UTILIZADA NA DATA ATUAL*/
) ENGINE=INNODB;

DROP TABLE IF EXISTS SEGUIDORES;
CREATE TABLE SEGUIDORES (
    USUARIO_ID INT NOT NULL,
    FOREIGN KEY(USUARIO_ID)/*CHAVE ESTRANGEIRA DE NOME USUARIO_ID*/
    REFERENCES USUARIOS(ID)/*REFERENCIANDO A COLUNA ID DA TABELA USUARIOS*/
    ON DELETE CASCADE,/*AO DELETAR UM USUARIO DA TABELA USUARIOS, SERÁ EXCLUSO OS SEGUIDORES DA TABELA SEGUIDORES*/

    SEGUIDOR_ID INT NOT NULL,
    FOREIGN KEY(SEGUIDOR_ID)
    REFERENCES USUARIOS(ID)
    ON DELETE CASCADE,

    PRIMARY KEY(USUARIO_ID, SEGUIDOR_ID)/*CHAVE PRIMÁRIA COMPOSTA*/
)ENGINE=INNODB;

DROP TABLE IF EXISTS PUBLICACOES;
CREATE TABLE PUBLICACOES(
    ID INT AUTO_INCREMENT PRIMARY KEY,
    TITULO VARCHAR(50) NOT NULL,
    CONTEUDO VARCHAR(100) NOT NULL,

    AUTOR_ID INT NOT NULL,
    FOREIGN KEY(AUTOR_ID)
    REFERENCES USUARIOS(ID)
    ON DELETE CASCADE,

    CURTIDAS INT DEFAULT 0,
    CRIADAEM TIMESTAMP DEFAULT CURRENT_TIMESTAMP
)ENGINE=INNODB;

